git:
  depth: 10

language: node_js

node_js:
  - "10"

script: npm run ci

matrix:
  fast_finish: true

notifications:
  email:
    - joshua@mervine.net
    - bootstrap@maxcdn.com

cache:
  directories:
    - node_modules
