git:
  depth: 5

language: node_js

node_js:
  - "10"

before_script:
  - curl https://v4.ifconfig.co/

script: npm run ci-with-coverage

after_success:
  - npm run coveralls

matrix:
  fast_finish: true

notifications:
  email:
    - joshua@mervine.net
    - bootstrap@maxcdn.com

cache:
  directories:
    - node_modules
