port: 3333

theme: 10 # bootswatch.themes[n]

authors:
- Joshua Mervine
- Justin Dorfman

description: Bootstrap CDN

favicon:
    # ico must be filesystem path, not web path
    ico: "public/images/favicon.ico"
    png: "/images/favicon.png"

google_analytics:
    account_id: UA-32253110-1
    domain_name: bootstrapcdn.com

####
# Turn stats on or off.
# - Use 'stub' to develop against test stub.
stats: true

####
# Note: stylesheets and javascript will be loaded
# in the order they are specified.
stylesheets:
- "//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css"

javascript:
    # scripts specified in the before group will be loaded
    # as blocking scripts inside the head tag
    #before:
    #
    # scripts specified in the after group will be loaded
    # as blocking scripts at the bottom of the page
    after:
    - "//code.jquery.com/jquery-1.10.1.min.js"
    - "//platform.twitter.com/widgets.js"
    - "//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"

####
# TODO: Perhaps move to a database (redis or mongo),
# or in to it's own configuration file.
#
# In the configs below, SWATCH_NAME will be replaced with
# the cosponding theme. SWATCH_VERSION will be replaced with
# the version specified.
bootswatch:
    version: "3.0.0"
    link: "http://bootswatch.com/SWATCH_NAME/"
    image: "http://bootswatch.com/SWATCH_NAME/thumbnail.png"
    bootstrap: "//netdna.bootstrapcdn.com/bootswatch/SWATCH_VERSION/SWATCH_NAME/bootstrap.min.css"
    themes:
        - amelia    # 0
        - cerulean  # 1
        - cosmo     # 2
        - cyborg    # 3
        - flatly    # 4
        - journal   # 5
        - readable  # 6
        - simplex   # 7
        - slate     # 8
        - spacelab  # 9
        - united    # 10

####
# TODO: Perhaps move to a database (redis or mongo),
# or in to it's own configuration file.
bootstrap:
    - version: "3.0.0"
      latest: true
      css_complete: "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"
      javascript:  "//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"

    - version: "2.3.2"
      css_complete: "//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css"
      css_no_icons: "//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css"
      javascript:   "//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"

    - version: "2.3.1"
      css_complete: "//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css"
      javascript:   "//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js"

    - version: "2.3.0"
      css_complete: "//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/css/bootstrap-combined.min.css"
      javascript:   "//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/js/bootstrap.min.js"

    - version: "2.2.2"
      css_complete: "//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/css/bootstrap-combined.min.css"
      css_no_icons: "//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/css/bootstrap.min.nr.css"
      javascript:   "//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js"

    - version: "2.2.1"
      css_complete: "//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/css/bootstrap-combined.min.css"
      javascript:   "//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/js/bootstrap.min.js"

    - version: "2.2.0"
      css_complete: "//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.0/css/bootstrap-combined.min.css"
      javascript:   "//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.0/js/bootstrap.min.js"

    - version: "2.1.1"
      css_complete: "//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/css/bootstrap-combined.min.css"
      javascript:   "//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/js/bootstrap.min.js"

    - version: "2.1.0"
      css_complete: "//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.0/css/bootstrap-combined.min.css"
      javascript:   "//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.0/js/bootstrap.min.js"

    - version: "2.0.4"
      css_complete: "//netdna.bootstrapcdn.com/twitter-bootstrap/2.0.4/css/bootstrap-combined.min.css"
      javascript:   "//netdna.bootstrapcdn.com/twitter-bootstrap/2.0.4/js/bootstrap.min.js"

# vim: ft=yaml sw=4 sts=4 et:
