port: 3333
theme: 1
siteurl: 'https://www.bootstrapcdn.com'
description: 'The recommended CDN for Bootstrap, Font Awesome and Bootswatch.'
title_suffix: 'BootstrapCDN by StackPath'
authors:
  - name: Justin Dorfman
    twitter: jdorfman
    url: 'https://twitter.com/jdorfman'
    work:
      text: StackShare
      url: 'https://stackshare.io/'
  - name: Joshua Mervine
    twitter: mervinej
    url: 'https://twitter.com/mervinej'
    work:
      text: Heroku
      url: 'https://www.heroku.com/'
  - name: XhmikosR
    twitter: XhmikosR
    url: 'https://xhmikosr.io/'
favicon:
  uri: /assets/img/favicons/favicon.ico
stylesheet:
  - name: iubenda
    uri: /assets/css/privacy_policy.css
javascript:
  - name: jquery
    uri: 'https://code.jquery.com/jquery-3.4.1.slim.min.js'
    sri: sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n
  - name: clipboardjs
    uri: /assets/js/vendor/clipboard.min.js
  - name: main
    uri: /assets/js/main.js
redirects:
  - name: legacy
    from: /legacy/
    to: /legacy/bootstrap/
  - name: alpha
    from: /alpha/
    to: /
  - name: beta
    from: /beta/
    to: /
  - name: bootswatch4
    from: /bootswatch4/
    to: /bootswatch/
