books:
  - name: 'Jump Start Bootstrap: Get Up to Speed With Bootstrap in a Weekend'
    img: /assets/img/books/Jump-Start-Bootstrap-Speed-Weekend.jpg
    url: 'https://www.amazon.com/Jump-Start-Bootstrap-Speed-Weekend/dp/0992279437/ref=as_li_ss_il?_encoding=UTF8&psc=1&refRID=2WP7MEQ0KPAHQS6YT117&linkCode=li3&tag=bcdn-20&linkId=b44f87f6e04d5eb7e6b49af61cd0e422'
  - name: 'Building Progressive Web Apps: Bringing the Power of Native to the Browser'
    img: /assets/img/books/Building-Progressive-Web-Apps-Bringing-ebook.jpg
    url: 'https://www.amazon.com/Building-Progressive-Web-Apps-Bringing-ebook/dp/B075HP52WY/ref=as_li_ss_il?ie=UTF8&linkCode=li3&tag=bcdn-20&linkId=013ca3a2eb57883d255384829ec0a6a2'
  - name: 'Coding For Dummies (For Dummies (Computer/Tech))'
    img: /assets/img/books/Coding-Dummies-Computer-Tech.jpg
    url: 'https://www.amazon.com/Coding-Dummies-Computer-Tech/dp/1119293324/ref=as_li_ss_il?ie=UTF8&linkCode=li3&tag=bcdn-20&linkId=fb405dc117a040e91557b45f6dc1094b'
  - name: 'Bootstrap in 24 Hours, Sams Teach Yourself'
    img: /assets/img/books/Bootstrap-Hours-Sams-Teach-Yourself-ebook.jpg
    url: 'https://www.amazon.com/Bootstrap-Hours-Sams-Teach-Yourself-ebook/dp/B017M8OWZQ/ref=as_li_ss_il?ie=UTF8&linkCode=li3&tag=bcdn-20&linkId=f8a39275b5204f5f2d0427a1ef1c4f83'
themesAd:
  - name: 'Velonic - Admin Dashboard & Frontend'
    img: /assets/img/themes/bootstrapbay-velonic-admin.jpg
    url: 'https://bootstrapbay.sjv.io/kVaX3'
  - name: 'ZTheme - Multipurpose Responsive Template'
    img: /assets/img/themes/ztheme-mulipurpose-responsive-template-B8068D9.jpg
    url: 'https://bootstrapbay.sjv.io/mNXyO'
  - name: 'Color Admin - Admin Template + Front End'
    img: /assets/img/themes/color-admin-admin-template-front-end.jpg
    url: 'https://wrapbootstrap.com/theme/color-admin-admin-template-front-end-WB0N89JMK?ref=bcdn'
  - name: 'Unify - Responsive Website Template'
    img: /assets/img/themes/unify-responsive-website-template.jpg
    url: 'https://wrapbootstrap.com/theme/unify-responsive-website-template-WB0412697?ref=bcdn'
  - name: 'The Project - Multipurpose Template'
    img: /assets/img/themes/the-project-multipurpose-template.jpg
    url: 'https://wrapbootstrap.com/theme/the-project-multipurpose-template-WB0F82581?ref=bcdn'
  - name: 'Vitality - One Page Bootstrap 4 Theme'
    img: /assets/img/themes/vitality-one-page-bootstrap-4-theme.jpg
    url: 'https://wrapbootstrap.com/theme/vitality-one-page-bootstrap-4-theme-WB02K3KK3?ref=bcdn'
showcase:
  - name: Microsoft Education
    img: /assets/img/showcase/microsoft-education.png
    lib: Font Awesome 4.3.0
    url: 'https://www.microsoft.com/en-us/education/default.aspx'
  - name: New York Post
    img: /assets/img/showcase/new-york-post.png
    lib: Font Awesome 4.0.3
    url: 'https://nypost.com/'
  - name: NBC News
    img: /assets/img/showcase/nbc-news.png
    lib: Font Awesome 4.0.3
    url: 'https://www.nbcnews.com/'
  - name: EA Help
    img: /assets/img/showcase/ea-help.png
    lib: Font Awesome 3.2.1
    url: 'https://help.ea.com/en/'
  - name: Stanford University
    img: /assets/img/showcase/stanford.png
    lib: Font Awesome 4.3.0
    url: 'https://www.stanford.edu/'
  - name: Go Doc
    img: /assets/img/showcase/godoc-org.png
    lib: Bootstrap 3.3.1
    url: 'https://godoc.org/'
  - name: Mozilla Webmaker API
    img: /assets/img/showcase/mozilla-webmaker.png
    lib: Bootstrap 3.0.3
    url: 'https://api.webmaker.org/docs'
  - name: New York University
    img: /assets/img/showcase/nyu.png
    lib: Font Awesome 4.2.0
    url: 'https://www.nyu.edu/'
  - name: Cracked
    img: /assets/img/showcase/cracked.png
    lib: 'Bootstrap 4.0.0'
    url: 'https://www.cracked.com/'
  - name: HP Support
    img: /assets/img/showcase/hp-support.png
    lib: Font Awesome 4.1.0
    url: 'https://support.hp.com/us-en'
  - name: Monster
    img: /assets/img/showcase/monster.png
    lib: Font Awesome 4.2.0
    url: 'https://www.monster.com/'
  - name: New Relic
    img: /assets/img/showcase/new-relic.png
    lib: Font Awesome 4.2.0
    url: 'https://newrelic.com/'
  - name: Nasdaq
    img: /assets/img/showcase/nasdaq.png
    lib: Font Awesome 4.4.0
    url: 'https://www.nasdaq.com/'
  - name: Creative Commons
    img: /assets/img/showcase/creative-commons.png
    lib: Bootstrap 3.2.0
    url: 'https://creativecommons.org/'
  - name: Udacity
    img: /assets/img/showcase/udacity.png
    lib: Bootstrap 3.0.0
    url: 'https://www.udacity.com/course/website-performance-optimization--ud884'
  - name: AdRoll
    img: /assets/img/showcase/llorda.png
    lib: Font Awesome 4.5.0
    url: 'https://help.adroll.com/hc/en-us'
  - name: Kubernetes Bootcamp
    img: /assets/img/showcase/kubernetes-bootcamp.png
    lib: Font Awesome 4.5.0
    url: 'https://kubernetesbootcamp.github.io/kubernetes-bootcamp/'
integrations:
  - name: Adobe Dreamweaver
    img: /assets/img/integrations/dreamweaver.png
    plat: Adobe Dreamweaver
    url: 'https://helpx.adobe.com/dreamweaver/using/bootstrap.html'
  - name: freeCodeCamp
    img: /assets/img/integrations/freecodecamp.png
    plat: Node.js
    url: 'https://www.freecodecamp.org/challenges/use-responsive-design-with-bootstrap-fluid-containers'
  - name: Bootstrap 3 Snippets
    img: /assets/img/integrations/atom-bootstrap3.png
    plat: Atom
    url: 'https://atom.io/packages/atom-bootstrap3'
  - name: Bootstrap 3
    img: /assets/img/integrations/drupal-bootstrap3.png
    plat: Drupal
    url: 'https://www.drupal.org/project/bootstrap'
  - name: Freight
    img: /assets/img/integrations/sentry-freight.png
    plat: Python
    url: 'https://github.com/getsentry/freight'
  - name: Bootstrap NBM
    img: /assets/img/integrations/bootstrap-nbm.png
    plat: NetBeans
    url: 'https://www.davidsalter.co.uk/bootstrap-cdn-plugin-for-netbeans-release-1-1-0/'
  - name: BootstrapCDN WP
    img: /assets/img/integrations/bootstrapcdn-wp.png
    plat: WordPress
    url: 'https://wordpress.org/plugins/bootstrapcdn/'
  - name: Light Bootstrap Dashboard
    img: /assets/img/integrations/light-bootstrap-dashboard.png
    plat: WebPlatform
    url: 'https://www.creative-tim.com/product/light-bootstrap-dashboard'
  - name: Radix Theme
    img: /assets/img/integrations/radix-theme-drupal.png
    plat: Drupal
    url: 'https://www.drupal.org/project/radix'
  - name: Bootstrap 3 Sublime Plugin
    img: /assets/img/integrations/bs3-sublime-plugin.png
    plat: Sublime
    url: 'https://github.com/JasonMortonNZ/bs3-sublime-plugin'
  - name: Bootstrap 3 Jade Sublime Plugin
    img: /assets/img/integrations/bs3-jade-sublime-plugin.png
    plat: Sublime
    url: 'https://github.com/rs459/bootstrap3-jade-sublime-plugin'
  - name: Bootstrap Editor and Builder
    img: /assets/img/integrations/bootply.png
    plat: Bootply
    url: 'https://www.bootply.com/'
  - name: React-Bootstrap
    img: /assets/img/integrations/react-bootstrap.png
    plat: React
    url: 'https://react-bootstrap.github.io/'
friends:
  - name: SecurityTrails
    url: 'https://securitytrails.com/'
  - name: Bootstrap
    url: 'https://getbootstrap.com/'
  - name: StackShare
    url: 'https://stackshare.io/'
  - name: nixCraft
    url: 'https://www.cyberciti.biz/'
  - name: EduBirdie
    url: 'https://edubirdie.com/'
    nofollow: false
